
name: 'transform'
version: '0.1'
profile: 'SampleDB'
config-version: 2

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "default"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

models:
  transform:
      +materialized: table
      staging:
        materialized: view
