select BBG_UNIQUE_CODE,TICKER,CPN,MATURITY,SERIES,"NAME",SHORT_NAME,ISSUER_INDUSTRY,MARKET_SECTOR_DES,CPN_FREQ,
CPN_TYP,MTY_TYP,CALC_TYP_DES,DAY_CNT,MARKET_ISSUE,COUNTRY,CRNCY,COLLAI_TYP,AMT_ISSUED,AMT_OUTSTANDING,MIN_PIECE,
MIN_INCREMENT,PAR_AMT,LEAD_MGR,EXCH_CODE,REDEMP_VAL,ANNOUNCE_DT,FIRST_SETTLE_DT,FIRST_CPN_DT,INT_ACC_DT,ISSUE_DT,
ISSUE_PX,ID_EUROCLEAR,ID_XTRAKIER,ID_SEDOL1,ID_SEDOL2,ID_CEDEL,ID_WERIPAPIER,ID_ISIN,ID_DUTCH,"ID_VALOREN ",ID_FRENCH,
ID_COMMON,ID_JAPAN,ID_BELGIUM,ID_DANISH,ID_AUSTRIAN,ID_LUXEMBOURG," ID_SWEDISH",ID_JAPAN_COMPANY,ID_SPAIN,ID_ITALY,
ID_BB_COMPANY,ID_BB_SECURITY,ID_CUSIP,NXT_CALL_DT,NXT_CALL_PX,NXT_PAR_CALL_DT,NXT_PUT_DT,NXT_PUT_PX,NXT_PAR_PUT_DT,
NXT_CPN_DT,NXT_SINK_DT,NXT_REFUND_DT,RIG_JCR,REFIX_FREQ,NXT_REFIX_DT,RESET_IDX,PFD_DVD_PAY_DT,PFD_EX_DVD_DT,PFD_RST_DVD,
CV_COMMON_TICKER,CV_COMMON_TICKER_EXCH,CV_CNVS_RAIIO,CV_UNTIL,CV_CNVS_FEXCH_RI,CV_PROV_PX,"CALLABLE ",SINKABLE,PUTABLE,
ID_BB_PARENT_CO,"PARENT_COMP_NAME ",PARENT_COMP_TICKER,"CNTRY_OF_ INCORPORATION",BASIC_SPREAD,INDUSTRY_SECTOR,INDUSTRY_GROUP,
INDUSTRY_SUBGROUP,COUNTRY_GUARANTOR,CNTRY_OF_DOMICILE,SECURITY_DES,144A_FLAG,FLT_BENCH_MULTIPLIER,SECURITY_TYP,CV_START_DT,
GUARANTOR_NAME,PREV_CPN_DT,NXT_SINK_AMT,CALL_DISCRETE,PUT_DISCRETE,ID_BB_UNIQUE,"LONG_COMP_NAME ",REDEMP_CRNCY,CPN_CRNCY,
DTC_ELIGIBLE,STRUCTURED_NOTE,PCT_PAR_QUOTED,PCS_QUOTE_TYP,IS_UNIT_TRADED," IS_REVERSE_CONVERTIBLE",TRADE_CRNCY,BEARER,
REGISTERED,"CALLED ",CALLED_DT," ISSUER",CALL_FEAIURE,PUT_FEATURE,PENULTIMATE_CPN_DT,FLT_CPN_CONVENTION,CUR_CPN,FLOAIER,
TRADE_STAIUS,CDR_COUNTRY_CODE,CDR_SETTLE_CODE,SEASONING_STAIUS,FINAL_MATURITY,PRVT_PLACE,CALC_TYP,REMOVAL_REASON,IS_PERPETUAL,IS_REGS,CALLED_PX,DEFAULTED,GILTS_EX_DVD_DT,MOST_RECENT_REPORIED_FACTOR,NXT_FACTOR_DT,
OID_BOND,DELIVERY_TYP,ID_SEDOL3,ID_SEDOL4,ID_SEDOL5,SEDOL1_COUNTRY_ISO,SEDOL2_COUNTRY_ISO,SEDOL3_COUNTRY_ISO,
SEDOL4_COUNTRY_ISO,"SEDOL5_COUNTR Y_ISO",ID_MIC1,ID_MIC2,ID_MIC3,ID_MIC4,ID_MIC5,CV_SH_PAR,DUAL_CRNCY,EXTENDIBLE,
EXCHANGEABLE,IS_SOFT_CALL,CV_MANDAIORY_CNVS,EU_SAVINGS_DIRECTIVE,ID_CUSIP_REAL,"INDUSTRY_SUBG ROUP_NUM",SECURITY_TYP2,
LAST_REFIX_DT,ISO_COUNTRY_GUARANTOR,DTC_REGISTERED,CALL_PARTIAL,CV_CNVS_PX,IS_CURRENT_GOVT,FIRST_CALL_DT_ISSUANCE,UNDL_ID_BB_UNIQUE,EST_CPN_FLAG,ID_BB_GUARANTOR," IS_DAY_PAYER",STEPUP_CPN,STEPUP_DT,CALC_MATURITY,"ID_EXCH_SYMBOL ",
CREDIT_ENHANCEMENTS,"INSURANCE _STATUS",JUNIOR,SENIOR,FLT_PAY_DAY,FLT_DAYS_PRIOR,INFLAIION_LINKED_INDICAIOR,DAYS_IO_SETTLE,TYPE_OF_BOND,REFERENCE_INDEX,BASE_CPI,CFI_CODE,CPN_FREQ_YLD_CNV,DAY_PAYER_FREQ,EX_DIV_DAYS,EX_DIV_CALENDAR,CONTINGENT_CONVERSION,
CONTRIB_DAIA_INDICAIOR,SECURITY_FACTORABLE,ID_BB_GLOBAL,SINKING_FUND_FACTOR,SINK_SCHEDULE_AMI_TYP,INDUSTRY_GROUP_NUM,
INDUSTRY_SECTOR_NUM,ISSUERS_STOCK,INFLAIION_LAG,"MAKE_WHOLE_CALL_SPR EAD",ISSUER_BULK,ID_BB_SEC_NUM_DES,"  FEED_SOURCE",
ID_BB_GLOBAL_COMPANY,ID_BB_GLOBAL_COMPANY_NAME,
case
when (ISSUE_PX is not null and PCS_QUOTE_TYP=2) then 100-cast(ISSUE_PX as numeric)
else cast(ISSUE_PX as numeric)
end as OfferPrice,
case
when (BEARER='Y' and REGISTERED='Y') then 'BEARREG'
when (BEARER='Y' and (REGISTERED='N' or REGISTERED is null)) then 'BEARER'
when ((BEARER='N' or BEARER is null) and REGISTERED='Y') then 'REGSTRD'
else 'UNKNOWN'
end as SecurityFormType,
case 
when TICKER='MBONO' then cast(MIN_PIECE as numeric)/100
when TICKER in ('BLFT','BLTN','BNTNB','BNTNC','BNTNF') then cast(MIN_PIECE as numeric)/1000
when PAR_AMT is not null then cast(MIN_PIECE as numeric)/cast(PAR_AMT as numeric)
else cast(MIN_PIECE as numeric)
end as minimumTradeSize,
case 
when TICKER='MBONO' then cast(MIN_INCREMENT as numeric)/100
when TICKER in ('BLFT','BLTN','BNTNB','BNTNC','BNTNF') then cast(MIN_INCREMENT as numeric)/1000
when PAR_AMT is not null then cast(MIN_INCREMENT as numeric)/cast(PAR_AMT as numeric)
else cast(MIN_INCREMENT as numeric)
end as RoundLotSize,
case
when PAR_AMT is not null then cast(PAR_AMT as numeric)
when PCT_PAR_QUOTED='N' then cast(1 as numeric)
when PCT_PAR_QUOTED='Y' then cast(100 as numeric)
end as NominalValueOfUnit,
case
when "CALLED "='Y' then 'FULLY'
else 'INCOMPLETE'
end as calleventtype
from {{ref('stg_bbg')}}
