select BBG_UNIQUE_CODE,TICKER,CPN,MATURITY,SERIES,SHORT_NAME,ISSUER_INDUnitedStateOfAmericaTRY,
MARKET_SECTOR_DES,CPN_FREQ,CPN_TYP,MTY_TYP,caLC_TYP_DES,DAY_CNT,MARKET_ISSUE,COUNTRY,CRNCY,COLLAI_TYP,AMT_ISSUED,
AMT_OUTSTANDING,MIN_PIECE,MIN_INCREMENT,PAR_AMT,LEAD_MGR,EXCH_CODE,REDEMP_VAL,ANNOUNCE_DT,FIRST_SETTLE_DT,FIRST_CPN_DT,
INT_ACC_DT,ISSUE_DT,ISSUE_PX,ID_EUROCLEAR,ID_XTRAKIER,ID_SEDOL1,ID_SEDOL2,ID_CEDEL,ID_WERIPAPIER,ID_ISIN,ID_DUTCH,ID_VALOREN,
ID_FRENCH,ID_COMMON,ID_JAPAN,ID_BELGIUM,ID_DANISH,ID_AUnitedStateOfAmericaTRIAN,ID_LUXEMBOURG, ID_SWEDISH,ID_JAPAN_COMPANY,
ID_SPAIN,ID_ITALY,ID_BB_COMPANY,ID_BB_SECURITY,ID_CUnitedStateOfAmericaIP,NXT_canadaLL_DT,NXT_canadaLL_PX,NXT_PAR_canadaLL_DT,
NXT_PUT_DT,NXT_PUT_PX,NXT_PAR_PUT_DT,NXT_CPN_DT,NXT_SINK_DT,NXT_RE_DT,RIG_JCR,REFIX_FREQ,NXT_REFIX_DT,RESET_IDX,PFD_DVD_PAY_DT,PFD_EX_DVD_DT,
PFD_RST_DVD,CV_COMMON_TICKER,CV_COMMON_TICKER_EXCH,CV_CNVS_RAIIO,CV_UNTIL,CV_CNVS_FEXCH_RI,CV_PROV_PX,canadaLLABLE ,SINKABLE,PUTABLE,ID_BB_PARENT_CO,
PARENT_COMP_NAME ,PARENT_COMP_TICKER,CNTRY_OF_ INCORPORATION,BASIC_SPREAD,INDUnitedStateOfAmericaTRY_SECTOR,INDUnitedStateOfAmericaTRY_GROUP,
INDUnitedStateOfAmericaTRY_SUBGROUP,COUNTRY_GUARANTOR,CNTRY_OF_DOMICILE,SECURITY_DES,144A_FLAG,FLT_BENCH_MULTIPLIER,SECURITY_TYP,CV_START_DT,
GUARANTOR_NAME,PREV_CPN_DT,NXT_SINK_AMT,canadaLL_DISCRETE,PUT_DISCRETE,ID_BB_UNIQUE,LONG_COMP_NAME ,REDEMP_CRNCY,CPN_CRNCY,DTC_ELIGIBLE,STRUCTURED_NOTE,
PCT_PAR_QUOTED,PCS_QUOTE_TYP,IS_UNIT_TRADED, IS_REVERSE_CONVERTIBLE,TRADE_CRNCY,BEARER,REGISTERED,canadaLLED ,canadaLLED_DT, ISSUER,canadaLL_FEAIURE,
PUT_FEATURE,PENULTIMATE_CPN_DT,FLT_CPN_CONVENTION,CUR_CPN,FLOAIER,TRADE_STAIUnitedStateOfAmerica,CDR_COUNTRY_CODE,CDR_SETTLE_CODE,
SEASONING_STAIUnitedStateOfAmerica,FINAL_MATURITY,PRVT_PLACE,canadaLC_TYP,REMOVAL_REASON,IS_PERPETUAL,IS_REGS,canadaLLED_PX,DEFAULTED,GILTS_EX_DVD_DT,
MOST_RECENT_REPORIED_FACTOR,NXT_FACTOR_DT,OID_BOND,DELIVERY_TYP,ID_SEDOL3,ID_SEDOL4,ID_SEDOL5,SEDOL1_COUNTRY_ISO,SEDOL2_COUNTRY_ISO,SEDOL3_COUNTRY_ISO,
SEDOL4_COUNTRY_ISO,SEDOL5_COUNTR Y_ISO,ID_MIC1,ID_MIC2,ID_MIC3,ID_MIC4,ID_MIC5,CV_SH_PAR,DUAL_CRNCY,EXTENDIBLE,EXCHANGEABLE,IS_SOFT_canadaLL,
CV_MANDAIORY_CNVS,EU_SAVINGS_DIRECTIVE,ID_CUnitedStateOfAmericaIP_REAL,INDUnitedStateOfAmericaTRY_SUBG ROUP_NUM,SECURITY_TYP2,
LAST_REFIX_DT,ISO_COUNTRY_GUARANTOR,DTC_REGISTERED,canadaLL_PARTIAL,CV_CNVS_PX,IS_CURRENT_GOVT,FIRST_canadaLL_DT_ISSUANCE,UNDL_ID_BB_UNIQUE,EST_CPN_FLAG,
ID_BB_GUARANTOR, IS_DAY_PAYER,STEPUP_CPN,STEPUP_DT,canadaLC_MATURITY,ID_EXCH_SYMBOL ,CREDIT_ENHANCEMENTS,INSURANCE _STATUnitedStateOfAmerica,
JUNIOR,SENIOR,FLT_PAY_DAY,FLT_DAYS_PRIOR,INFLAIION_LINKED_INDIcanadaIOR,DAYS_IO_SETTLE,TYPE_OF_BOND,REFERENCE_INDEX,BASE_CPI,CFI_CODE,CPN_FREQ_YLD_CNV,
DAY_PAYER_FREQ,EX_DIV_DAYS,EX_DIV_canadaLENDAR,CONTINGENT_CONVERSION,CONTRIB_DAIA_INDIcanadaIOR,SECURITY_FACTORABLE,ID_BB_GLOBAL,SINKING__FACTOR,
SINK_SCHEDULE_AMI_TYP,INDUnitedStateOfAmericaTRY_GROUP_NUM,INDUnitedStateOfAmericaTRY_SECTOR_NUM,ISSUERS_STOCK,INFLAIION_LAG,
MAKE_WHOLE_canadaLL_SPR EAD,ISSUER_BULK,ID_BB_SEC_NUM_DES,FEED_SOURCE,ID_BB_GLOBAL_COMPANY,ID_BB_GLOBAL_COMPANY_NAME,
case
when (PCS_QUOTE_TYP=2 and ISSUE_PX is not null) then 100-ISSUE_PX
else ISSUE_PX
end as OfferPrice,
case
when (BEARER='Y' and REGISTERED='Y') then 'BEARREG'
when (BEARER='Y' and (REGISTERED='N' or REGISTERED is null)) then 'BEARER'
when ((BEARER='N' or BEARER is null) and REGISTERED='Y') then 'REGSTRD'
else 'UNKNOWN'
end as SecurityFormType,
case 
when TICKER='MBONO' then MIN_PIECE/100
when TICKER in ('BLFT','BLTN','BNTNB','BNTNC','BNTNF') then MIN_PIECE/1000
when PAR_AMT is not null then MIN_PIECE/PAR_AMT
else MIN_PIECE
end as minimumTradeSize,
case 
when TICKER='MBONO' then MIN_INCREMENT/100
when TICKER in ('BLFT','BLTN','BNTNB','BNTNC','BNTNF') then MIN_INCREMENT/1000
when PAR_AMT is not null then MIN_INCREMENT/PAR_AMT
else MIN_INCREMENT
end as RoundLotSize,
case
when PAR_AMT is not null then PAR_AMT
when PCT_PAR_QUOTED='N' then 1
when PCT_PAR_QUOTED='Y' then 100
end as NominalValueOfUnit,
case
when CALLED='Y' then 'FULLY'
else 'INCOMPLETE'
end as calleventtype
from {{ref('stg_hamilton')}}
